// <auto-generated />
namespace Animart.Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterShipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterShipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201602081510278_alterShipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
